<a href="https://colab.research.google.com/github/kvraagul/Innomatics_Internship_APR_21/blob/main/Task_10(EDA).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**INNOMATICS INTERNSHIP APRIL 2021**

**TASK 10 EXPLORATORY DATA ANALYSIS**

# Importing the Libraries

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

# Importing the Dataset

In [ ]:
dataset = pd.read_excel('aspiring_minds_employability_outcomes_2015.xlsx')

# Description of Dataset 

In [ ]:
dataset.head()

Unnamed: 0   Salary  ... nueroticism openess_to_experience
0      train   420000  ...     1.35490               -0.4455
1      train   500000  ...    -0.10760                0.8637
2      train   325000  ...    -0.86820                0.6721
3      train  1100000  ...    -0.40780               -0.9194
4      train   200000  ...     0.09163               -0.1295

[5 rows x 38 columns]

In [ ]:
dataset.shape

(3998, 38)

In [ ]:
dataset.describe()

Salary  10percentage  ...  nueroticism  openess_to_experience
count  3.998000e+03   3998.000000  ...  3998.000000            3998.000000
mean   3.076998e+05     77.925443  ...    -0.169033              -0.138110
std    2.127375e+05      9.850162  ...     1.007580               1.008075
min    3.500000e+04     43.000000  ...    -2.643000              -7.375700
25%    1.800000e+05     71.680000  ...    -0.868200              -0.669200
50%    3.000000e+05     79.150000  ...    -0.234400              -0.094300
75%    3.700000e+05     85.670000  ...     0.526200               0.502400
max    4.000000e+06     97.760000  ...     3.352500               1.822400

[8 rows x 26 columns]

In [ ]:
X = dataset.iloc[:, 2:].values
y = dataset.iloc[:, 1 ].values

In [ ]:
print(X)

[[Timestamp('2012-06-01 00:00:00') 'present' 'senior quality engineer'
  ... 0.5269 1.3549 -0.4455]
 [Timestamp('2013-09-01 00:00:00') 'present' 'assistant manager' ...
  1.2396 -0.1076 0.8637]
 [Timestamp('2014-06-01 00:00:00') 'present' 'systems engineer' ...
  0.1637 -0.8682 0.6721]
 ...
 [Timestamp('2013-07-01 00:00:00') 'present'
  'associate software engineer' ... -1.5051 -1.3184 -0.7615]
 [Timestamp('2014-07-01 00:00:00') datetime.datetime(2015, 1, 1, 0, 0)
  'software developer' ... -0.4511 -0.3612 -0.0943]
 [Timestamp('2013-02-01 00:00:00') 'present' 'senior systems engineer'
  ... -0.6343 1.32552999999999 -0.6035]]


In [ ]:
print(y)

[420000 500000 325000 ... 320000 200000 400000]


# Missing Data

In [ ]:
dataset.isnull().sum()

Unnamed: 0               0
ID                       0
Salary                   0
DOJ                      0
DOL                      0
Designation              0
JobCity                  0
Gender                   0
DOB                      0
10percentage             0
10board                  0
12graduation             0
12percentage             0
12board                  0
CollegeID                0
CollegeTier              0
Degree                   0
Specialization           0
collegeGPA               0
CollegeCityID            0
CollegeCityTier          0
CollegeState             0
GraduationYear           0
English                  0
Logical                  0
Quant                    0
Domain                   0
ComputerProgramming      0
ElectronicsAndSemicon    0
ComputerScience          0
MechanicalEngg           0
ElectricalEngg           0
TelecomEngg              0
CivilEngg                0
conscientiousness        0
agreeableness            0
extraversion             0
n

**There is no missing Data in the given Dataset**

# Encoding Categorical Data

  **For Independent Variable**

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[0.0 0.0 0.0 ... 0.5269 1.3549 -0.4455]
 [0.0 0.0 0.0 ... 1.2396 -0.1076 0.8637]
 [0.0 0.0 0.0 ... 0.1637 -0.8682 0.6721]
 ...
 [0.0 0.0 0.0 ... -1.5051 -1.3184 -0.7615]
 [0.0 0.0 0.0 ... -0.4511 -0.3612 -0.0943]
 [0.0 0.0 0.0 ... -0.6343 1.32552999999999 -0.6035]]


# Splitting the Dataset to training set and test set


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [ ]:
print(X_train)

[[0.0 0.0 0.0 ... 0.8171 -0.9953 -0.7615]
 [0.0 0.0 0.0 ... 0.7785 -0.2344 -1.244]
 [0.0 0.0 0.0 ... 1.0859 2.1743 0.6721]
 ...
 [0.0 0.0 0.0 ... -0.9245 -0.6428 -0.6035]
 [0.0 0.0 0.0 ... 0.2366 0.2973 -0.2875]
 [0.0 0.0 0.0 ... -0.9245 -1.5828 0.6603]]


In [ ]:
print(X_test)

[[0.0 0.0 0.0 ... -1.0697 0.1798 -0.6035]
 [0.0 0.0 0.0 ... -0.4511 -0.8682 -0.6692]
 [0.0 0.0 0.0 ... 0.7785 -1.5021 0.4805]
 ...
 [0.0 0.0 0.0 ... 0.4711 -1.8824 -0.6692]
 [0.0 0.0 0.0 ... 0.4711 0.3995 -1.0524]
 [0.0 0.0 0.0 ... -0.0537 -0.4078 0.9763]]


In [ ]:
print(y_train)

[110000 340000 300000 ... 150000 120000 300000]


In [ ]:
print(y_test)


[ 440000  300000  325000  145000  180000  325000  400000  100000  500000
  200000  310000  435000  450000  450000  500000  290000  505000   50000
  620000  350000 3500000  450000  200000  305000  520000  330000  350000
  180000  555000  240000  325000  205000  180000  210000  425000  180000
  500000  375000  145000  430000  120000  600000  415000  240000  450000
  415000  240000  190000  145000  190000  200000  355000  360000  450000
  500000  120000  400000  180000  225000  380000  440000  300000  180000
  305000  240000  325000  225000  120000  420000  150000  305000  275000
  200000  335000  400000  450000  100000  300000  315000  140000  390000
  200000  240000  300000  375000  330000  150000  310000  400000  630000
  700000  320000  220000  405000  120000  650000  400000  100000  650000
  320000  410000  250000  200000  600000  305000  275000  120000  250000
  420000  360000  315000  360000  180000  310000  510000  520000 1200000
  375000  380000  420000  305000  145000  180000  3